sim:
  field_size: [9, 6]
  time_delta: 0.1
  render_resolution: 80
  length: 2000

misc:
  num_robots: 4

ball:
  gen:
    friction_factor: 0.8
    kick_intensity: 5.0
    kick_prop: 0.005
    ball_noise: 0.1

robot:
  height: 0.8
  gen:
    position:
      walk_speed_factor: 0.5
      noise: 0.02
      walk_prop: 0.1
      stop_prop: 0.01
    orientation:
      turn_speed_factor: 1
      noise: 0.0
      turn_prop: 0.1
      stop_prop: 0.01


rl:
  observation:
    vec:
      num: 9
      base_position: True
      base_heading: True
      camera_position: False
      neck_joint_position: True
      neck_joint_position_history: False
      sin_phase: True
      action_history: False
      estimated_ball_state: True
      estimated_robot_states: False
    maps:
      observation_maps: False
      resolution: 10
      estimated_robot_states_map: True
      view_history_map: True
      view_history_map_decay: 0.99
  action:
    mode: "Absolute"  # Pattern, Velocity, Position, Absolute
  reward:
    base: 1
    ball_visibility: 1
    robot_visibility: 1
    sin_demonstration_mse: -1
    ball_confidence: 0
    robot_confidence: 0
    field_coverage_mean: 0
    field_coverage_std: 0

